### ISSUE TITLE
acquire produces corrupt tar file when trying to collect a file which cannot be read for its whole length

### ISSUE THREAD

**Issue by mischw** [fox-it/acquire#61]
I am using `acquire` on a raw image to get out some files. Within this image there are a couple of special (sparse? corrupt?) files which originate from a Firefox profile. The files in question are all sqlite files:

`/root/.mozilla/firefox/[some-id].default-esr/cookies.sqlite` and some other sqlite files found in this profile folder.

This file (cookies.sqlite) is reported to be 524288 bytes in size by `ls` or `stat`. But when actually read it stops after 98304 bytes (In my experiments `cp`, `hexdump` and `md5sum` all did not go beyond). After that it is only zero bytes anyway, so I doubt this is a coincidence.

 

Now when using the `dir` output type it seems to work without errors:

```

  Module |    Success |    Failure |    Missing |      Empty

------------------------------------------------------------

cli-args |      11477 |            |            |          

------------------------------------------------------------

   Total |      11477 |          0 |          0 |          0

------------------------------------------------------------

```

It should be noted though that the file `cookies.sqlite` for example was only 98304 bytes at destination as a result. I guess this behavior is _ok_ depending on how you look at it. But a warning message might be appropriate.

 

The more serious problem happened when using the `tar` output type. Judging by the log this works _mostly_ fine. In my example there are 11477 files of which only 5 failed:

```

Done collecting artifacts:

------------------------------------------------------------

  Module |    Success |    Failure |    Missing |      Empty

------------------------------------------------------------

cli-args |      11472 |          5 |            |

------------------------------------------------------------

   Total |      11472 |          5 |          0 |          0

------------------------------------------------------------

```

The 5 failed files were the sqlite files mentioned before.

 

But now when inspecting the tar file it seems to be corrupted:

```shell

tar -tvf out.tar | wc -l

tar: Skipping to next header

tar: Exiting with failure status due to previous errors

7152

```

It seems to only contain 7152 of the 11472 files. 7-Zip on Windows opens the tar even without complaints but many files are missing / not shown.

When using the tar switch `-i`/`--ignore-zeros` it finds at least all the files that were successfully collected.

```shell

tar -itvf out.tar | wc -l

tar: Skipping to next header

tar: Skipping to next header

tar: Skipping to next header

tar: Exiting with failure status due to previous errors

11469

```

What I learned is that if the file to be collected cannot be read for the length attributed to it, adding it to the tar file will fail, and the tar becomes somewhat corrupted.

 

 

What the logs says:

```

[2023-05-02 17:09:16,850] [ERROR] Failed to collect file

Traceback (most recent call last):

  File "/root/py3venv_dissect/lib/python3.11/site-packages/acquire/collector.py", line 279, in collect_file

    self.output.write_entry(outpath, entry, size)

  File "/root/py3venv_dissect/lib/python3.11/site-packages/acquire/outputs/base.py", line 54, in write_entry

    self.write(output_path, fh, entry, size)

  File "/root/py3venv_dissect/lib/python3.11/site-packages/acquire/outputs/tar.py", line 103, in write

    self.tar.addfile(info, fh)

  File "/usr/lib/python3.11/tarfile.py", line 2030, in addfile

    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)

  File "/usr/lib/python3.11/tarfile.py", line 250, in copyfileobj

    raise exception("unexpected end of data")

OSError: unexpected end of data

[2023-05-02 17:09:16,853] [INFO ] - Collecting file /root/.mozilla/firefox/[some-id].default-esr/cookies.sqlite: OSError('unexpected end of data')

```

 

I tried to reproduce this error by building a sparse file manually with `truncate -s 1M file.img` and adding it to a tar using `tarfile` but to my surprise it worked. Maybe Firefox's sqlite files are created somehow special?

Let me know if I could provide more info.

**Comment by Schamper** [comment]
This sounds suspiciously like a filesystem bug that we fixed very recently - so recent that it has not yet made it's way into the stable release yet :smile::
- https://github.com/fox-it/dissect.xfs/commit/a605e02422d4c2497134b2b62ea1a6b8c4c070b7
- https://github.com/fox-it/dissect.extfs/commit/5218f0d0d59f797cf69f6e94811034fc4a038b83.

Could you try installing the prerelease versions of these packages (`pip install -U --pre {dissect.extfs,dissect.xfs}`) to see if that fixes the issue?

**Comment by mischw** [comment]
Thank you! That actually fixed it. Will test some more next week.

On another note: If I have ideas for enhancements/features, should I open a new issue or discuss it somewhere first?

**Comment by Schamper** [comment]
We don't have a formalized process yet, but Github Discussions looks like a good place to discuss: https://github.com/fox-it/acquire/discussions/categories/ideas

Ideas or suggestions that don't fit in a particular project can be put in the Discussions space of the Dissect namespace package: https://github.com/fox-it/dissect
